version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    ignore:
      - dependency-name: prettier
    commit-message:
      prefix: "chore(deps)"
    labels:
      - "dependencies"
    reviewers:
      - pt232
