name: Documentation Report
description: Point out problems or errors in the documentation
title: "[DOCS] "
labels: ["documentation"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report any problems or issues that you have encountered with the documentation!
  - type: textarea
    id: description
    attributes:
      label: Describe the issue with documentation
      description: Please describe the issue with documentation you have.
    validations:
      required: true
